---
  - name: install memcached
    action: apt name=memcached

  - name: write memcached.conf
    action: template src=templates/memcached.conf.j2 dest=/etc/memcached.conf mode=0644
    notify:
      - restart memcached
